db_host: 192.168.1.31
db_port: '3306'
db_name: work_website_monitor
db_user: work
db_pass: xtasia
mail_transport: smtp
smtp_server: mailtrap.io
smtp_port: '2525'
smtp_encryption: ''
smtp_user: 449623fa3e18dcea5
smtp_pass: 870b7f224f2c9f
